name: TypeScript Check

on:
  pull_request:
    branches: [main]

jobs:
  type-check:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Run TypeScript check
        run: npm run ts:check
